### ISSUE TITLE
Cannot open font resource

### ISSUE THREAD

**Issue by Charlex** [pastpages/storytracker#83]
Running into an error in a python script.

This is the code: 

```
import storytracker
import os

OUTPUT_DIR = os.path.dirname(os.path.realpath(__file__)) + "/archive/"

storytracker.archive("http://www.latimes.com", OUTPUT_DIR)
```

This is the exception:
```
DEBUG:storytracker.archive:Archiving URL: http://www.latimes.com
DEBUG:storytracker.get:Requesting http://www.latimes.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): www.latimes.com
DEBUG:requests.packages.urllib3.connectionpool:"GET / HTTP/1.1" 200 50991
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    storytracker.archive("http://www.latimes.com")
  File "/home/charlex/lat/waybacker/local/lib/python2.7/site-packages/storytracker/archive.py", line 59, in archive
    obj = storytracker.ArchivedURL(url, now, html)
  File "/home/charlex/lat/waybacker/local/lib/python2.7/site-packages/storytracker/analysis.py", line 67, in __init__
    35
  File "/home/charlex/lat/waybacker/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 240, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/home/charlex/lat/waybacker/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 137, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource
```

[These lines](https://github.com/pastpages/storytracker/blob/master/storytracker/analysis.py#L65-L68) in the analysis file reference the font that PIL is trying to call.

I'm probably just missing something simple..

**Comment by Charlex** [comment]
Figured it out by myself. `/fonts/` was not present in the `/site-packages/storytracker/`. I installed using pip, but I guess the fonts folder didn't come through. Odd too, because pypi has fonts in their tar.gz file. Also, templates isn't there, but I haven't ran into any missing templates issues so far.

This might not be an issue, but I'll leave it open for @palewire to close.

**Comment by palewire** [comment]
How did you install the package?

**Comment by Charlex** [comment]
pip install storytracker into a virtualenv

**Comment by palewire** [comment]
Alright. Thanks for the bug report. It's possible something is off with the package because the fonts should install there. I'll give it a look.

**Comment by palewire** [comment]
I think I got it. This should fix any problems if I got it right.

``` bash
$ pip install storytracker --upgrade
```
